/*
	Copyright (c) 2004-2007, The Dojo Foundation
	All Rights Reserved.

	Licensed under the Academic Free License version 2.1 or above OR the
	modified BSD license. For more information on Dojo licensing, see:

		http://dojotoolkit.org/book/dojo-book-0-9/introduction/licensing
*/


if(!dojo._hasResource["dijit._tree.dndContainer"]){dojo._hasResource["dijit._tree.dndContainer"]=true;dojo.provide("dijit._tree.dndContainer");dojo.require("dojo.dnd.common");dojo.require("dojo.dnd.Container");dojo.declare("dijit._tree.dndContainer",null,{constructor:function(_1,_2){this.tree=_1;this.node=_1.domNode;dojo.mixin(this,_2);this.map={};this.current=null;this.ContainerState="";dojo.addClass(this.node,"dojoDndContainer");if(!(_2&&_2._skipStartup)){this.startup();}this.events=[dojo.connect(this.node,"onmouseover",this,"onMouseOver"),dojo.connect(this.node,"onmouseout",this,"onMouseOut"),dojo.connect(this.node,"ondragstart",dojo,"stopEvent"),dojo.connect(this.node,"onselectstart",dojo,"stopEvent")];},getItem:function(_3){return this.selection[_3];},onMouseOver:function(e){var n=e.relatedTarget;while(n){if(n==this.node){break;}try{n=n.parentNode;}catch(x){n=null;}}if(!n){this._changeState("Container","Over");this.onOverEvent();}n=this._getChildByEvent(e);if(this.current==n){return;}if(this.current){this._removeItemClass(this.current,"Over");}if(n){this._addItemClass(n,"Over");}this.current=n;},onMouseOut:function(e){for(var n=e.relatedTarget;n;){if(n==this.node){return;}try{n=n.parentNode;}catch(x){n=null;}}if(this.current){this._removeItemClass(this.current,"Over");this.current=null;}this._changeState("Container","");this.onOutEvent();},_changeState:function(_8,_9){var _a="dojoDnd"+_8;var _b=_8.toLowerCase()+"State";dojo.removeClass(this.node,_a+this[_b]);dojo.addClass(this.node,_a+_9);this[_b]=_9;},_getChildByEvent:function(e){var _d=e.target;if(_d&&dojo.hasClass(_d,"dijitTreeLabel")){return _d;}return null;},markupFactory:function(_e,_f){_f._skipStartup=true;return new dijit._tree.dndContainer(_e,_f);},_addItemClass:function(_10,_11){dojo.addClass(_10,"dojoDndItem"+_11);},_removeItemClass:function(_12,_13){dojo.removeClass(_12,"dojoDndItem"+_13);},onOverEvent:function(){console.log("onOverEvent parent");},onOutEvent:function(){}});}