/*
	Copyright (c) 2004-2007, The Dojo Foundation
	All Rights Reserved.

	Licensed under the Academic Free License version 2.1 or above OR the
	modified BSD license. For more information on Dojo licensing, see:

		http://dojotoolkit.org/book/dojo-book-0-9/introduction/licensing
*/


(function(){if(typeof this["djConfig"]=="undefined"){this.djConfig={};}if((!this["console"])||(!console["firebug"])){this.console={};}var cn=["assert","count","debug","dir","dirxml","error","group","groupEnd","info","log","profile","profileEnd","time","timeEnd","trace","warn"];var i=0,tn;while((tn=cn[i++])){if(!console[tn]){console[tn]=function(){};}}if(typeof this["dojo"]=="undefined"){this.dojo={};}var d=dojo;dojo.global=this;var _5={isDebug:false,libraryScriptUri:"",preventBackButtonFix:true,delayMozLoadingFix:false};for(var _6 in _5){if(typeof djConfig[_6]=="undefined"){djConfig[_6]=_5[_6];}}var _7=["Browser","Rhino","Spidermonkey","Mobile"];var t;while(t=_7.shift()){d["is"+t]=false;}dojo.locale=djConfig.locale;dojo.version={major:1,minor:0,patch:2,flag:"",revision:Number("$Rev: 11832 $".match(/[0-9]+/)[0]),toString:function(){with(d.version){return major+"."+minor+"."+patch+flag+" ("+revision+")";}}};if(typeof OpenAjax!="undefined"){OpenAjax.hub.registerLibrary("dojo","http://dojotoolkit.org",d.version.toString());}dojo._mixin=function(_9,_a){var _b={};for(var x in _a){if(_b[x]===undefined||_b[x]!=_a[x]){_9[x]=_a[x];}}if(d["isIE"]&&_a){var p=_a.toString;if(typeof p=="function"&&p!=_9.toString&&p!=_b.toString&&p!="\nfunction toString() {\n    [native code]\n}\n"){_9.toString=_a.toString;}}return _9;};dojo.mixin=function(_e,_f){for(var i=1,l=arguments.length;i<l;i++){d._mixin(_e,arguments[i]);}return _e;};dojo._getProp=function(_12,_13,_14){var obj=_14||d.global;for(var i=0,p;obj&&(p=_12[i]);i++){obj=(p in obj?obj[p]:(_13?obj[p]={}:undefined));}return obj;};dojo.setObject=function(_18,_19,_1a){var _1b=_18.split("."),p=_1b.pop(),obj=d._getProp(_1b,true,_1a);return (obj&&p?(obj[p]=_19):undefined);};dojo.getObject=function(_1e,_1f,_20){return d._getProp(_1e.split("."),_1f,_20);};dojo.exists=function(_21,obj){return !!d.getObject(_21,false,obj);};dojo["eval"]=function(_23){return d.global.eval?d.global.eval(_23):eval(_23);};d.deprecated=d.experimental=function(){};})();