/*
	Copyright (c) 2004-2007, The Dojo Foundation
	All Rights Reserved.

	Licensed under the Academic Free License version 2.1 or above OR the
	modified BSD license. For more information on Dojo licensing, see:

		http://dojotoolkit.org/book/dojo-book-0-9/introduction/licensing
*/


if(!dojo._hasResource["dijit.form.FilteringSelect"]){dojo._hasResource["dijit.form.FilteringSelect"]=true;dojo.provide("dijit.form.FilteringSelect");dojo.require("dijit.form.ComboBox");dojo.declare("dijit.form.FilteringSelect",[dijit.form.MappedTextBox,dijit.form.ComboBoxMixin],{labelAttr:"",labelType:"text",_isvalid:true,isValid:function(){return this._isvalid;},_callbackSetLabel:function(_1,_2,_3){if(_2&&_2.query[this.searchAttr]!=this._lastQuery){return;}if(!_1.length){if(!this._hasFocus){this.valueNode.value="";}dijit.form.TextBox.superclass.setValue.call(this,undefined,!this._hasFocus);this._isvalid=false;this.validate(this._hasFocus);}else{this._setValueFromItem(_1[0],_3);}},_openResultList:function(_4,_5){if(_5.query[this.searchAttr]!=this._lastQuery){return;}this._isvalid=_4.length!=0;this.validate(true);dijit.form.ComboBoxMixin.prototype._openResultList.apply(this,arguments);},getValue:function(){return this.valueNode.value;},_getValueField:function(){return "value";},_setValue:function(_6,_7,_8){this.valueNode.value=_6;dijit.form.FilteringSelect.superclass.setValue.call(this,_6,_8,_7);this._lastDisplayedValue=_7;},setValue:function(_9,_a){var _b=this;var _c=function(_d,_e){if(_d){if(_b.store.isItemLoaded(_d)){_b._callbackSetLabel([_d],undefined,_e);}else{_b.store.loadItem({item:_d,onItem:function(_f,_10){_b._callbackSetLabel(_f,_10,_e);}});}}else{_b._isvalid=false;_b.validate(false);}};this.store.fetchItemByIdentity({identity:_9,onItem:function(_11){_c(_11,_a);}});},_setValueFromItem:function(_12,_13){this._isvalid=true;this._setValue(this.store.getIdentity(_12),this.labelFunc(_12,this.store),_13);},labelFunc:function(_14,_15){return _15.getValue(_14,this.searchAttr);},onkeyup:function(evt){},_doSelect:function(tgt){this.item=tgt.item;this._setValueFromItem(tgt.item,true);},setDisplayedValue:function(_18){if(this.store){var _19={};this._lastQuery=_19[this.searchAttr]=_18;this.textbox.value=_18;this._lastDisplayedValue=_18;this.store.fetch({query:_19,queryOptions:{ignoreCase:this.ignoreCase,deep:true},onComplete:dojo.hitch(this,this._callbackSetLabel)});}},_getMenuLabelFromItem:function(_1a){if(this.labelAttr){return {html:this.labelType=="html",label:this.store.getValue(_1a,this.labelAttr)};}else{return dijit.form.ComboBoxMixin.prototype._getMenuLabelFromItem.apply(this,arguments);}},postMixInProperties:function(){dijit.form.ComboBoxMixin.prototype.postMixInProperties.apply(this,arguments);dijit.form.MappedTextBox.prototype.postMixInProperties.apply(this,arguments);}});}