/*
	Copyright (c) 2004-2007, The Dojo Foundation
	All Rights Reserved.

	Licensed under the Academic Free License version 2.1 or above OR the
	modified BSD license. For more information on Dojo licensing, see:

		http://dojotoolkit.org/book/dojo-book-0-9/introduction/licensing
*/


if(!dojo._hasResource["dijit.form.TextBox"]){dojo._hasResource["dijit.form.TextBox"]=true;dojo.provide("dijit.form.TextBox");dojo.require("dijit.form._FormWidget");dojo.declare("dijit.form.TextBox",dijit.form._FormWidget,{trim:false,uppercase:false,lowercase:false,propercase:false,maxLength:"",templateString:"<input class=\"dojoTextBox\" dojoAttachPoint='textbox,focusNode' name=\"${name}\"\n\tdojoAttachEvent='onmouseenter:_onMouse,onmouseleave:_onMouse,onfocus:_onMouse,onblur:_onMouse,onkeyup,onkeypress:_onKeyPress'\n\tautocomplete=\"off\" type=\"${type}\"\n\t/>\n",baseClass:"dijitTextBox",attributeMap:dojo.mixin(dojo.clone(dijit.form._FormWidget.prototype.attributeMap),{maxLength:"focusNode"}),getDisplayedValue:function(){return this.filter(this.textbox.value);},getValue:function(){return this.parse(this.getDisplayedValue(),this.constraints);},setValue:function(_1,_2,_3){var _4=this.filter(_1);if((typeof _4==typeof _1)&&(_3==null||_3==undefined)){_3=this.format(_4,this.constraints);}if(_3!=null&&_3!=undefined){this.textbox.value=_3;}dijit.form.TextBox.superclass.setValue.call(this,_4,_2);},setDisplayedValue:function(_5){this.textbox.value=_5;this.setValue(this.getValue(),true);},forWaiValuenow:function(){return this.getDisplayedValue();},format:function(_6,_7){return ((_6==null||_6==undefined)?"":(_6.toString?_6.toString():_6));},parse:function(_8,_9){return _8;},postCreate:function(){this.textbox.setAttribute("value",this.getDisplayedValue());this.inherited("postCreate",arguments);if(this.srcNodeRef){dojo.style(this.textbox,"cssText",this.style);this.textbox.className+=" "+this["class"];}this._layoutHack();},_layoutHack:function(){if(dojo.isFF==2&&this.domNode.tagName=="TABLE"){var _a=this.domNode;var _b=_a.style.opacity;_a.style.opacity="0.999";setTimeout(function(){_a.style.opacity=_b;},0);}},filter:function(_c){if(_c==undefined||_c==null){return "";}else{if(typeof _c!="string"){return _c;}}if(this.trim){_c=dojo.trim(_c);}if(this.uppercase){_c=_c.toUpperCase();}if(this.lowercase){_c=_c.toLowerCase();}if(this.propercase){_c=_c.replace(/[^\s]+/g,function(_d){return _d.substring(0,1).toUpperCase()+_d.substring(1);});}return _c;},_onBlur:function(){this.setValue(this.getValue(),(this.isValid?this.isValid():true));},onkeyup:function(){}});}