/*
	Copyright (c) 2004-2007, The Dojo Foundation
	All Rights Reserved.

	Licensed under the Academic Free License version 2.1 or above OR the
	modified BSD license. For more information on Dojo licensing, see:

		http://dojotoolkit.org/book/dojo-book-0-9/introduction/licensing
*/


if(!dojo._hasResource["dojo.fx"]){dojo._hasResource["dojo.fx"]=true;dojo.provide("dojo.fx");dojo.provide("dojo.fx.Toggler");dojo.fx.chain=function(_1){var _2=_1.shift();var _3=_2;dojo.forEach(_1,function(_4){dojo.connect(_3,"onEnd",_4,"play");_3=_4;});return _2;};dojo.fx.combine=function(_5){var _6=new dojo._Animation({curve:[0,1]});if(!_5.length){return _6;}_6.duration=_5[0].duration;dojo.forEach(_5,function(_7){dojo.forEach(["play","pause","stop"],function(e){if(_7[e]){dojo.connect(_6,e,_7,e);}});});return _6;};dojo.declare("dojo.fx.Toggler",null,{constructor:function(_9){var _t=this;dojo.mixin(_t,_9);_t.node=_9.node;_t._showArgs=dojo.mixin({},_9);_t._showArgs.node=_t.node;_t._showArgs.duration=_t.showDuration;_t.showAnim=_t.showFunc(_t._showArgs);_t._hideArgs=dojo.mixin({},_9);_t._hideArgs.node=_t.node;_t._hideArgs.duration=_t.hideDuration;_t.hideAnim=_t.hideFunc(_t._hideArgs);dojo.connect(_t.showAnim,"beforeBegin",dojo.hitch(_t.hideAnim,"stop",true));dojo.connect(_t.hideAnim,"beforeBegin",dojo.hitch(_t.showAnim,"stop",true));},node:null,showFunc:dojo.fadeIn,hideFunc:dojo.fadeOut,showDuration:200,hideDuration:200,show:function(_b){return this.showAnim.play(_b||0);},hide:function(_c){return this.hideAnim.play(_c||0);}});dojo.fx.wipeIn=function(_d){_d.node=dojo.byId(_d.node);var _e=_d.node,s=_e.style;var _10=dojo.animateProperty(dojo.mixin({properties:{height:{start:function(){s.overflow="hidden";if(s.visibility=="hidden"||s.display=="none"){s.height="1px";s.display="";s.visibility="";return 1;}else{var _11=dojo.style(_e,"height");return Math.max(_11,1);}},end:function(){return _e.scrollHeight;}}}},_d));dojo.connect(_10,"onEnd",function(){s.height="auto";});return _10;};dojo.fx.wipeOut=function(_12){var _13=_12.node=dojo.byId(_12.node);var s=_13.style;var _15=dojo.animateProperty(dojo.mixin({properties:{height:{end:1}}},_12));dojo.connect(_15,"beforeBegin",function(){s.overflow="hidden";s.display="";});dojo.connect(_15,"onEnd",function(){s.height="auto";s.display="none";});return _15;};dojo.fx.slideTo=function(_16){var _17=(_16.node=dojo.byId(_16.node));var top=null;var _19=null;var _1a=(function(n){return function(){var cs=dojo.getComputedStyle(n);var pos=cs.position;top=(pos=="absolute"?n.offsetTop:parseInt(cs.top)||0);_19=(pos=="absolute"?n.offsetLeft:parseInt(cs.left)||0);if(pos!="absolute"&&pos!="relative"){var ret=dojo.coords(n,true);top=ret.y;_19=ret.x;n.style.position="absolute";n.style.top=top+"px";n.style.left=_19+"px";}};})(_17);_1a();var _1f=dojo.animateProperty(dojo.mixin({properties:{top:{end:_16.top||0},left:{end:_16.left||0}}},_16));dojo.connect(_1f,"beforeBegin",_1f,_1a);return _1f;};}