/*
	Copyright (c) 2004-2007, The Dojo Foundation
	All Rights Reserved.

	Licensed under the Academic Free License version 2.1 or above OR the
	modified BSD license. For more information on Dojo licensing, see:

		http://dojotoolkit.org/book/dojo-book-0-9/introduction/licensing
*/


if(!dojo._hasResource["dojo.io.script"]){dojo._hasResource["dojo.io.script"]=true;dojo.provide("dojo.io.script");dojo.io.script={get:function(_1){var _2=this._makeScriptDeferred(_1);var _3=_2.ioArgs;dojo._ioAddQueryToUrl(_3);this.attach(_3.id,_3.url);dojo._ioWatch(_2,this._validCheck,this._ioCheck,this._resHandle);return _2;},attach:function(id,_5){var _6=dojo.doc.createElement("script");_6.type="text/javascript";_6.src=_5;_6.id=id;dojo.doc.getElementsByTagName("head")[0].appendChild(_6);},remove:function(id){dojo._destroyElement(dojo.byId(id));if(this["jsonp_"+id]){delete this["jsonp_"+id];}},_makeScriptDeferred:function(_8){var _9=dojo._ioSetArgs(_8,this._deferredCancel,this._deferredOk,this._deferredError);var _a=_9.ioArgs;_a.id="dojoIoScript"+(this._counter++);_a.canDelete=false;if(_8.callbackParamName){_a.query=_a.query||"";if(_a.query.length>0){_a.query+="&";}_a.query+=_8.callbackParamName+"=dojo.io.script.jsonp_"+_a.id+"._jsonpCallback";_a.canDelete=true;_9._jsonpCallback=this._jsonpCallback;this["jsonp_"+_a.id]=_9;}return _9;},_deferredCancel:function(_b){_b.canceled=true;if(_b.ioArgs.canDelete){dojo.io.script._deadScripts.push(_b.ioArgs.id);}},_deferredOk:function(_c){if(_c.ioArgs.canDelete){dojo.io.script._deadScripts.push(_c.ioArgs.id);}if(_c.ioArgs.json){return _c.ioArgs.json;}else{return _c.ioArgs;}},_deferredError:function(_d,_e){if(_e.ioArgs.canDelete){if(_d.dojoType=="timeout"){dojo.io.script.remove(_e.ioArgs.id);}else{dojo.io.script._deadScripts.push(_e.ioArgs.id);}}console.debug("dojo.io.script error",_d);return _d;},_deadScripts:[],_counter:1,_validCheck:function(_f){var _10=dojo.io.script;var _11=_10._deadScripts;if(_11&&_11.length>0){for(var i=0;i<_11.length;i++){_10.remove(_11[i]);}dojo.io.script._deadScripts=[];}return true;},_ioCheck:function(dfd){if(dfd.ioArgs.json){return true;}var _14=dfd.ioArgs.args.checkString;if(_14&&eval("typeof("+_14+") != 'undefined'")){return true;}return false;},_resHandle:function(dfd){if(dojo.io.script._ioCheck(dfd)){dfd.callback(dfd);}else{dfd.errback(new Error("inconceivable dojo.io.script._resHandle error"));}},_jsonpCallback:function(_16){this.ioArgs.json=_16;}};}