/*
	Copyright (c) 2004-2007, The Dojo Foundation
	All Rights Reserved.

	Licensed under the Academic Free License version 2.1 or above OR the
	modified BSD license. For more information on Dojo licensing, see:

		http://dojotoolkit.org/book/dojo-book-0-9/introduction/licensing
*/


if(!dojo._hasResource["dijit._editor.plugins.AlwaysShowToolbar"]){dojo._hasResource["dijit._editor.plugins.AlwaysShowToolbar"]=true;dojo.provide("dijit._editor.plugins.AlwaysShowToolbar");dojo.declare("dijit._editor.plugins.AlwaysShowToolbar",null,{_handleScroll:true,setEditor:function(e){this.editor=e;e.onLoadDeferred.addCallback(dojo.hitch(this,this.enable));},enable:function(d){this._updateHeight();this._connects=[dojo.connect(window,"onscroll",this,"globalOnScrollHandler"),dojo.connect(this.editor,"onNormalizedDisplayChanged",this,"_updateHeight")];return d;},_updateHeight:function(){var e=this.editor;if(!e.isLoaded){return;}if(e.height){return;}var _4=dojo.marginBox(e.editNode).h;if(dojo.isOpera){_4=e.editNode.scrollHeight;}if(!_4){_4=dojo.marginBox(e.document.body).h;}if(_4==0){console.debug("Can not figure out the height of the editing area!");return;}if(_4!=this._lastHeight){this._lastHeight=_4;dojo.marginBox(e.iframe,{h:this._lastHeight});}},_lastHeight:0,globalOnScrollHandler:function(){var _5=dojo.isIE&&dojo.isIE<7;if(!this._handleScroll){return;}var _6=this.editor.toolbar.domNode;var db=dojo.body;if(!this._scrollSetUp){this._scrollSetUp=true;this._scrollThreshold=dojo._abs(_6,true).y;}var _8=dojo._docScroll().y;if(_8>this._scrollThreshold&&_8<this._scrollThreshold+this._lastHeight){if(!this._fixEnabled){var _9=dojo.marginBox(_6);this.editor.iframe.style.marginTop=_9.h+"px";if(_5){_6.style.left=dojo._abs(_6).x;if(_6.previousSibling){this._IEOriginalPos=["after",_6.previousSibling];}else{if(_6.nextSibling){this._IEOriginalPos=["before",_6.nextSibling];}else{this._IEOriginalPos=["last",_6.parentNode];}}dojo.body().appendChild(_6);dojo.addClass(_6,"IEFixedToolbar");}else{with(_6.style){position="fixed";top="0px";}}dojo.marginBox(_6,{w:_9.w});_6.style.zIndex=2000;this._fixEnabled=true;}var _a=(this.height)?parseInt(this.editor.height):this.editor._lastHeight;if(_8>(this._scrollThreshold+_a)){_6.style.display="none";}else{_6.style.display="";}}else{if(this._fixEnabled){this.editor.iframe.style.marginTop="";with(_6.style){position="";top="";zIndex="";display="";}if(_5){_6.style.left="";dojo.removeClass(_6,"IEFixedToolbar");if(this._IEOriginalPos){dojo.place(_6,this._IEOriginalPos[1],this._IEOriginalPos[0]);this._IEOriginalPos=null;}else{dojo.place(_6,this.editor.iframe,"before");}}_6.style.width="";this._fixEnabled=false;}}},destroy:function(){this._IEOriginalPos=null;this._handleScroll=false;dojo.forEach(this._connects,dojo.disconnect);if(dojo.isIE&&dojo.isIE<7){dojo.removeClass(this.editor.toolbar.domNode,"IEFixedToolbar");}}});}