/*
	Copyright (c) 2004-2007, The Dojo Foundation
	All Rights Reserved.

	Licensed under the Academic Free License version 2.1 or above OR the
	modified BSD license. For more information on Dojo licensing, see:

		http://dojotoolkit.org/book/dojo-book-0-9/introduction/licensing
*/


if(!dojo._hasResource["dijit._base.place"]){dojo._hasResource["dijit._base.place"]=true;dojo.provide("dijit._base.place");dijit.getViewport=function(){var _1=dojo.global;var _2=dojo.doc;var w=0,h=0;if(dojo.isMozilla){var _5,_6,_7,_8;if(_2.body.clientWidth>_2.documentElement.clientWidth){_5=_2.documentElement.clientWidth;_7=_2.body.clientWidth;}else{_7=_2.documentElement.clientWidth;_5=_2.body.clientWidth;}if(_2.body.clientHeight>_2.documentElement.clientHeight){_6=_2.documentElement.clientHeight;_8=_2.body.clientHeight;}else{_8=_2.documentElement.clientHeight;_6=_2.body.clientHeight;}w=(_7>_1.innerWidth)?_5:_7;h=(_8>_1.innerHeight)?_6:_8;}else{if(!dojo.isOpera&&_1.innerWidth){w=_1.innerWidth;h=_1.innerHeight;}else{if(dojo.isIE&&_2.documentElement&&_2.documentElement.clientHeight){w=_2.documentElement.clientWidth;h=_2.documentElement.clientHeight;}else{if(dojo.body().clientWidth){w=dojo.body().clientWidth;h=dojo.body().clientHeight;}}}}var _9=dojo._docScroll();return {w:w,h:h,l:_9.x,t:_9.y};};dijit.placeOnScreen=function(_a,_b,_c,_d){var _e=dojo.map(_c,function(_f){return {corner:_f,pos:_b};});return dijit._place(_a,_e);};dijit._place=function(_10,_11,_12){var _13=dijit.getViewport();if(!_10.parentNode||String(_10.parentNode.tagName).toLowerCase()!="body"){dojo.body().appendChild(_10);}var _14=null;for(var i=0;i<_11.length;i++){var _16=_11[i].corner;var pos=_11[i].pos;if(_12){_12(_16);}var _18=_10.style.display;var _19=_10.style.visibility;_10.style.visibility="hidden";_10.style.display="";var mb=dojo.marginBox(_10);_10.style.display=_18;_10.style.visibility=_19;var _1b=(_16.charAt(1)=="L"?pos.x:Math.max(_13.l,pos.x-mb.w)),_1c=(_16.charAt(0)=="T"?pos.y:Math.max(_13.t,pos.y-mb.h)),_1d=(_16.charAt(1)=="L"?Math.min(_13.l+_13.w,_1b+mb.w):pos.x),_1e=(_16.charAt(0)=="T"?Math.min(_13.t+_13.h,_1c+mb.h):pos.y),_1f=_1d-_1b,_20=_1e-_1c,_21=(mb.w-_1f)+(mb.h-_20);if(_14==null||_21<_14.overflow){_14={corner:_16,aroundCorner:_11[i].aroundCorner,x:_1b,y:_1c,w:_1f,h:_20,overflow:_21};}if(_21==0){break;}}_10.style.left=_14.x+"px";_10.style.top=_14.y+"px";return _14;};dijit.placeOnScreenAroundElement=function(_22,_23,_24,_25){_23=dojo.byId(_23);var _26=_23.style.display;_23.style.display="";var _27=_23.offsetWidth;var _28=_23.offsetHeight;var _29=dojo.coords(_23,true);_23.style.display=_26;var _2a=[];for(var _2b in _24){_2a.push({aroundCorner:_2b,corner:_24[_2b],pos:{x:_29.x+(_2b.charAt(1)=="L"?0:_27),y:_29.y+(_2b.charAt(0)=="T"?0:_28)}});}return dijit._place(_22,_2a,_25);};}